require("after.ftplugin.html")
require("after.ftplugin.css")
require("after.ftplugin.scss")
require("after.ftplugin.json")
require("after.ftplugin.js")
require("after.ftplugin.py")
require("after.ftplugin.cs")
